import { Suit } from "../types/Suit";

export const PlayerInfo = [
    {
        name: '',
        position: 0,
        status: -1,
        chips: 0,
        cards: [],
        betSize: 0,
        rebuys: 0,
        permissions: "player",
    },
    {
        name: '',
        position: 1,
        status: -1,
        chips: 0,
        cards: [],
        betSize: 0,
        rebuys: 0,
        permissions: "player",
    },
    {
        name: '',
        position: 2,
        status: -1,
        chips: 0,
        cards: [],
        betSize: 0,
        rebuys: 0,
        permissions: "player",
    },
    {
        name: '',
        position: 3,
        status: -1,
        chips: 0,
        cards: [],
        betSize: 0,
        rebuys: 0,
        permissions: "player",
    },
    {
        name: '',
        position: 4,
        status: -1,
        chips: 0,
        cards: [],
        betSize: 0,
        rebuys: 0,
        permissions: "player",
    },
    {
        name: '',
        position: 5,
        status: -1,
        chips: 0,
        cards: [],
        betSize: 0,
        rebuys: 0,
        permissions: "player",
    },
    {
        name: '',
        position: 6,
        status: -1,
        chips: 0,
        cards: [],
        betSize: 0,
        rebuys: 0,
        permissions: "player",
    },
    {
        name: '',
        position: 7,
        status: -1,
        chips: 0,
        cards: [],
        betSize: 0,
        rebuys: 0,
        permissions: "player",
    }
]
